language: node_js
node_js:
    - '10'
install:
    - npm install && npm test
script:
    - npm run build
deploy:
    provider: pages
    skip-cleanup: true
    github-token: $GITHUB_TOKEN
    keep-history: true
    project: ./dist/
    on:
        branch: master
